export const PROJECT_ERROR_CODES = {
    NAME_REQUIRED: 'ERR_PROJECT_001',
    NAME_EXISTS: 'ERR_PROJECT_002',
    DESCRIPTION_REQUIRED: 'ERR_PROJECT_003'
}

export const CHAPTER_ERROR_CODES = {
    NAME_REQUIRED: 'ERR_CHAPTER_001',
    PROJECT_NOT_FOUND: 'ERR_CHAPTER_002',
    NAME_EXISTS: 'ERR_CHAPTER_003',
    CHAPTER_NOT_FOUND: 'ERR_CHAPTER_004', 
    SERVER_ERROR: 'ERR_CHAPTER_005'
}